[tool.poetry]
name = "extract_thinker"
version = "0.0.32"
description = "Library to extract data from files and documents agnositicaly using LLMs"
authors = ["JÃºlio Almeida <enoch3712@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.14"
pydantic = "^2.10.2"
litellm = "^1.53.2"
pytesseract = "^0.3.10"
pillow = "^10.3.0"
python-docx = "^1.1.0"
xlrd = "^2.0.1"
pypdfium2 = "^4.29.0"
instructor = "^1.7.0"
python-dotenv = "^1.0.1"
cachetools = "^5.3.3"
pyyaml = "^6.0.1"
tiktoken = {version = "^0.8.0", python = ">=3.9,<3.13"}
openpyxl = "^3.1.2"
azure-ai-formrecognizer = "^3.3.3"
google-cloud-documentai = "^3.0.1"
boto3 = "^1.34.161"
pdfplumber = "^0.11.4"
pypdf = "^5.1.0"
docx2txt = "^0.8"
python-magic = "^0.4.27"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.2"
black = "^21.9b0"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
pytest = "^8.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
